# Auth App Service
apiVersion: v1
kind: Service
metadata:
  name: learner-auth
spec:
  selector:
    app: learner-auth
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
# Auth App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learner-auth
  template:
    metadata:
      labels:
        app: learner-auth
    spec:
      containers:
        - name: learner-auth
          image: viburoshin25/learner-auth:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            initialDelaySeconds: 10
